#!/bin/sh

set -e

export PKI_DEFAULT_COUNTRY="${PKI_DEFAULT_COUNTRY:-DE}"
export PKI_DEFAULT_STATE="${PKI_DEFAULT_STATE:-BaWue}"
export PKI_DEFAULT_LOCATION="${PKI_DEFAULT_LOCATION:-Stuttgart}"
export PKI_DEFAULT_ORG="${PKI_DEFAULT_ORG:-Serialize}"
export PKI_DEFAULT_ORG_UNIT="${PKI_DEFAULT_ORG_UNIT:-IT}"


function create_csr()
{
    TMPL="$1"
    CN="$2"

    cat "/usr/local/share/cfssl/csr-${TMPL}.json" |
    sed "s/%%%CN%%%/${CN}/g" |
    sed "s/%%%COUNTRY%%%/${PKI_DEFAULT_COUNTRY}/g" |
    sed "s/%%%STATE%%%/${PKI_DEFAULT_STATE}/g" |
    sed "s/%%%LOCATION%%%/${PKI_DEFAULT_LOCATION}/g" |
    sed "s/%%%ORG%%%/${PKI_DEFAULT_ORG}/g" |
    sed "s/%%%ORGUNIT%%%/${PKI_DEFAULT_ORG_UNIT}/g" > "/etc/cfssl/csr-${TMPL}.json"
}

if [ ! -f /etc/cfssl/cfssl.conf ] ; then


    if [ -z "$PKI_CA_AUTH_KEY" ]; then
        export PKI_CA_AUTH_KEY="$(hexdump -n 16 -e "4/4 \"%08X\" 1 \"\n\"" /dev/random)"
        echo "Auth-Key Generated: $PKI_CA_AUTH_KEY"
    fi

    cat "/usr/local/share/cfssl/cfssl.conf" |
    sed "s/%%%AUTH_KEY%%%/${PKI_CA_AUTH_KEY}/g" > "/etc/cfssl/cfssl.conf"

fi

if [ ! -f /etc/cfssl/ca.pem ] || [ ! -f /etc/cfssl/ca-key.pem ] ; then

    export PKI_CA_ROOT_CN="${PKI_CA_ROOT_CN:-Serialize Root CA}"
    create_csr "ca-root" "${PKI_CA_ROOT_CN}"

    cfssl gencert \
        -initca "/etc/cfssl/csr-ca-root.json" | 
        cfssljson -bare /etc/cfssl/ca-root

    rm /etc/cfssl/ca-root.csr /etc/cfssl/csr-ca-root.json

    export PKI_CA_INTERMEDIATE_CN="${PKI_CA_INTERMEDIATE_CN:-Serialize Intermediate CA}"
    create_csr "ca-intermediate" "${PKI_CA_INTERMEDIATE_CN}"

    cfssl gencert \
        -ca "/etc/cfssl/ca-root.pem" \
        -ca-key "/etc/cfssl/ca-root-key.pem" \
        -config "/etc/cfssl/cfssl.conf" \
        -profile "intermediate_ca" \
        "/etc/cfssl/csr-ca-intermediate.json" | 
        cfssljson -bare /etc/cfssl/ca-intermediate

    rm /etc/cfssl/ca-intermediate.csr /etc/cfssl/csr-ca-intermediate.json
    ln -s /etc/cfssl/ca-intermediate.pem /etc/cfssl/ca.pem
    ln -s /etc/cfssl/ca-intermediate-key.pem /etc/cfssl/ca-key.pem

    cat /etc/cfssl/ca-root.pem > /etc/cfssl/ca-bundle.crt

fi

if [ "$1" != "cfssl" ]; then

	exec cfssl "$@"

elif [[ "$1" == "cfssl" ]] && [[ "$2" == "serve" ]] && [[ $# -eq 2 ]]; then

    SERVE_ARGS=()

    [ -f /etc/cfssl/ca.pem ] && SERVE_ARGS+=("-ca=ca.pem")
    [ -f /etc/cfssl/ca-key.pem ] && SERVE_ARGS+=("-ca-key=ca-key.pem")
    [ -f /etc/cfssl/ca-bundle.crt ] && SERVE_ARGS+=("-ca-bundle=ca-bundle.crt")
    [ -f /etc/cfssl/int-bundle.crt ] && SERVE_ARGS+=("-int-bundle=int-bundle.crt")
    [ -f /etc/cfssl/db-config.json ] && SERVE_ARGS+=("-db-config=db-config.json")
    [ -f /etc/cfssl/cfssl.conf ] && SERVE_ARGS+=("-config=cfssl.conf")

    SERVE_ARGS+=("-address=0.0.0.0")
    SERVE_ARGS+=("-port=8888")

    exec cfssl serve "${SERVE_ARGS[@]}"

else

    exec "$@"

fi





